@startuml
title Game State Diagram

[*] --> Running: The game has been started
Running --> Win: The player has found the treasure
Running --> Fail: The player has been caught by a teacher
Running --> Fail: The time has run out
Win --> [*]: The game has ended
Fail --> [*]: The game has ended

@enduml