@startuml person
title Person State Diagram

[*] --> Active
Active --> KnockedOut: knock out
KnockedOut --> Active: KO timer ran out

Active --> [*]: killed

KnockedOut: entry/startKnockOutTimer()

@enduml