@startuml rag
title Wet Rag State Diagram

[*] --> Unequipped: /wetTime = 15
Unequipped --> Active: equip()
Active --> Unequipped: drop()
Active --> Active: update(deltaTime) \n/wetTime -= deltaTime
Active --> Dry: wetTime <= 0
Dry --> [*]

Dry: entry/make self useless
@enduml