@startuml rag
title Wet Rag State Diagram

[*] --> Unequiped: /wetTime = 15
Unequiped --> Active: equip()
Active --> Unequiped: drop()
Active --> Active: update(deltaTime) \n/wetTime -= deltaTime
Active --> Dry: wetTime <= 0
Dry --> [*]

Dry: entry/make self useless
@enduml