@startuml room
title Room State Diagram
[*] --> Neutral
Neutral --> Poisioned: poison()

Neutral --> [*]: merge() && smaller
Poisioned --> [*]: merge() && smaller

Poisioned: entry/ startPoisionTimer()

@enduml