@startuml test-use-cases

:Felhasználó: as User

left to right direction

usecase Ajtóhasználat as use_door

package "Tárgy lerakás/felvétel"{
    usecase Maszkeldobás as drop_mask
    usecase Maszkfelvétel as pick_mask
    usecase "Hallgató felveszi a logarlécet" as student_pick_slide
    usecase "Oktató felveszi a logarlécet" as teacher_pick_slide
}

package "Tárgy használat"{
    usecase Maszkhasználat as use_mask
    usecase "TVSZ használat" as use_code
    usecase "Söröspohár használat" as use_beer
    usecase "Nedves táblatörlő rongy használat" as use_rag
    usecase "Camembert használat" as use_camambert
    usecase "Tranzisztor használat" as use_trans
    usecase "Tranzisztor\nösszekapcsolása" as linking
}

usecase "Sör hatása" as beer_effect
usecase "Rongy hatása" as rag_effect

package "Szoba manipuláció"{
    usecase "Sima szobák összeolvadása" as merge_room_normal
    usecase "Szobák összeolvadása" as merge_room
    usecase "Elátkozott szoba\najtók elrejtése" as cursed_room_hide
    usecase "Elátkozott szoba\najtók megjelenítése" as cursed_room_show
    usecase "Szoba osztódás" as split_room
}

package "Szoba frissítése"{
    usecase "Szoba frissítése: hallgatók" as upd_room_students
    usecase "Szoba frissítése: hallgató és oktató" as upd_room_student_teacher
    usecase "Szoba frissítése: hallgató és gáz effect" as upd_room_student_gas
    usecase "Szoba frissítése: hallgató maszkkal és gáz effect" as upd_room_student_mask_gas
    usecase "Szoba frissítése: oktató és rongy effect" as upd_room_teacher_rag
}


User -- use_door

User -- pick_mask
User -- drop_mask
User -- student_pick_slide
User -- teacher_pick_slide

User -up- use_mask
User -up- use_beer
User -up- use_code
User -up- use_camambert
User -up- use_rag
User -up- use_trans
use_trans .> linking : <<include>>

User -up- merge_room
User -up- merge_room_normal
User -up- cursed_room_show
User -up- cursed_room_hide
User -up- split_room

User -- upd_room_students
User -- upd_room_student_teacher
User -- upd_room_student_gas
User -- upd_room_student_mask_gas
User -- upd_room_teacher_rag

User -- beer_effect
User -- rag_effect

@enduml