@startuml link-transistor-create

title Create "Link Transistor" test
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main
participant "transistor : Transistor" as transistor
participant "other : Transistor" as other

main++

create transistor
main --> transistor : <<create>>

create other
main --> other : <<create>>

@enduml
