@startuml room-update-student-teacher-create
title Create "Update Room with a Student and a Teacher" test
hide footbox
participant "Main" as main
participant "room : Room" as room
participant "student : Student" as student
participant "teacher : Teacher" as teacher

main++
create room
main --> room : <<create>>
create student
main --> student : <<create>>
create teacher
main --> teacher : <<create>>
main -> room ++: enterPerson(student)
return
main -> room ++: enterPerson(teacher)
return

@enduml