@startuml room-update-rag-effect
title Create "Update Room with Rag Effect" test
hide footbox

skinparam SequenceReferenceBackgroundColor white

participant Main
participant "room : Room" as room
participant "teacher : Teacher" as teacher
participant "ragEffect : RagEffect" as rag

Main++
create room
Main --> room : <<create>>
create teacher
Main --> teacher : <<create>>
Main -> room ++ : enter(teacher)
return
create rag
Main --> rag : <<create>>

Main -> room ++ : addEffect(ragEffect)
return

@enduml