@startuml room-hide-doors-create

title Create "Hide Doors" test
hide footbox
participant "Main" as main
participant "room : Room" as room
participant "otherRoom : Room" as other
participant "door : Door" as door
participant "door2 : Door" as door2

main++

create room
main --> room : <<create>>
create other
main --> other : <<create>>
create door
main --> door : Door(room, otherRoom)
create door2
main --> door2 : Door(otherRoom, room)

@enduml