@startuml room-merge-create
title Create "Merge Room" test
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main
participant "room1 : Room" as r1
participant "room2 : Room" as r2
participant "door : Door" as door

create r1
main -> r1 : <<create>>
create r2
main -> r2 : <<create>>
create door
main -> door : <<create>>
main -> door : move(r1, r2)
return

@enduml