@startuml student-use-code-of-studies-create

title Create "Code Of Studies Protection" test
hide footbox

participant "Main" as main
participant "student : Student" as student
participant "teacher : Teacher" as teacher
participant "codeOfStudies : CodeOfStudies" as codeOfStudies

main++
create student
main --> student : <<create>>
create teacher
main --> teacher : <<create>>
create codeOfStudies
main --> codeOfStudies : <<create>>
main -> student ++ : addItem(codeOfStudies)
student --> main

@enduml
