@startuml student-use-mask

title Create "Use Mask" test
hide footbox

participant "main : Main" as main
participant "mask : Mask" as mask
participant "student : Student" as student

main++
create mask
main-> mask : <<create>>
create student
main-> student : <<create>>
main -> mask ++: setPerson(student)
return

@enduml
