@startuml student-protected-by-beer-create

title Create "Student Gets Protected by Beer" test
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main

participant "student : Student" as student
participant "beerEffect : BeerEffect" as beer

main++
create student
main --> student : <<create>>
create beer
main --> beer : <<create>>
main -> student ++: addEffect(beerEffect)
return
main -> student ++: setEliminated(true)
return

@enduml
