@startuml student-use-transistor-create
title Create "Use Transistor" test
hide footbox

participant "Main" as main
participant "student : Student" as student
create "inventory : Inventory" as inventory
participant "transistor1 : Transistor" as tr
participant "transistor2 : Transistor" as tr2
participant "room : Room" as room
participant "targetRoom : Room" as targetRoom

main++
create student
main --> student : <<create>>
create inventory
student --> inventory : <<create>>
create tr
main --> tr : <<create>>
create tr2
main --> tr2 : <<create>>
create room
main --> room : <<create>>
create targetRoom
main --> targetRoom : <<create>>
main -> student ++ : addItem(transistor)
return


@enduml