@startuml person-add-item-create

title Create "Add Item to Person" test
hide footbox
autoactivate on
participant "main : Main" as main
participant "student : Student" as student
participant "inventory : Inventory" as inventory
participant "mask : Mask" as mask

create student
main --> student : <<create>>
create inventory
student --> inventory : <<create>>
create mask
main --> mask : <<create>>

@enduml