@startuml item-beer-use-create
title Create "Camembert" test
hide footbox

participant "main : Main" as main
participant "student : Student" as student
participant "room : Room" as room
participant "camembert : Camembert" as camembert

main++
create student
main --> student : <<create>>
create room
main --> room : <<create>>
create camembert
main --> camembert : <<create>>
main -> student ++ : addItem(beer)
return

@enduml