@startuml student-use-beer-create
title Create "Use Beer" test
hide footbox

participant "Main" as main
participant "student : Student" as student
participant "beer : Beer" as beer

main++
create student
main --> student : <<create>>
create beer
main --> beer : <<create>>
main -> student ++ : addItem(beer)
return


@enduml