@startuml camambert
title Use Camambert
hide footbox
autoactivate on

participant "camambert : Camambert" as c
participant "person : Person" as p
participant "room : Room" as r

[-> c : use(person)
    c -> p : applyEffect(gasEffect)
        p -> r : applyEffect(gasEffect)
        return 
    return
    c -> p : removeItem(camambert)
    return
return
@enduml