@startuml camambert-sequence

hide footbox

 -> Camambert ++: use(p: Person)
    Camambert -> Room ++: makeToxic()
    loop person in Room
        Room -> Person ++: knockOut(duration: int)
        Room <-- Person --
    end
Camambert <-- Room --
<-- Camambert --
	
@enduml