@startuml camembert
title Use Camembert
hide footbox
autoactivate on

participant "camembert : Camembert" as c
participant "person : Person" as p
participant "room : Room" as r

[-> c : use(person)
    c -> p : applyEffect(gasEffect)
        p -> r : applyEffect(gasEffect)
        return 
    return
    c -> p : removeItem(camembert)
    return
return
@enduml