@startuml door
hide footbox
participant "door : Door" as door
participant "next : Room" as next
participant "previous : Room" as prev

[-> door ++: use(p: Person, from: Room) 
opt correct direction
	door -> next ++: enterRoom(p: Person)
	alt has capacity
		next --> door: success
		door -> prev ++: leaveRoom(p: Person)
		prev --> door --
		[<-- door : success
	else
		next --> door --: failed
	end
end
[<-- door --: failed

@enduml