@startuml door-use
title Use Door
hide footbox
participant "door : Door" as door
participant "next : Room" as next
participant "person : Person" as person

[-> door ++: use(person, from: Room) 
opt correct direction
	door -> next ++: enter(person)
		opt has capacity
			next -> person ++: enterRoom(next)
			return
		end
	return
end
return
@enduml