@startuml door-sequence
hide footbox
participant "door : Door" as door
participant "next : Room" as next
participant "previous : Room" as prev

[-> door ++: use(p: Person, from: Room) 
alt correct direction
	door -> next ++: enterRoom(p: Person)
	alt has capacity
		next --> door: success
		door -> prev ++: leaveRoom(p: Person)
		deactivate prev
		[<-- door : success
	else
		next --> door --: failed
		[<-- door : failed
	end
else
	[<-- door : failed
end

@enduml