@startuml effect-mask-apply

title Mask Protection
hide footbox

participant "effect : MaskEffect" as effect
participant "target : Student" as target

[-> effect ++: applyToStudent(target)
note right: Same for teacher
	effect -> effect ++: apply(target)
	effect -> target ++: setKnockOut(false)
	return
	deactivate
return

@enduml
