@startuml item-code-of-studies-use

title Code Of Studies Protection
hide footbox

participant "codeOfStudies : CodeOfStudies" as codeOfStudies
participant "person : Person" as person

[-> codeOfStudies ++: useAgainst(target)
	codeOfStudies -> person ++: protectFromTeacher(target)
	return
return

@enduml
