@startuml item-beer-use
title Use Beer
hide footbox

participant "beer : Beer" as beer
participant "person : Person" as person

[-> beer ++: use()
create "beerEffect : BeerEffect" as beerEffect
beer -> beerEffect : <<create>>
beer -> person ++ : applyEffect(beerEffect)
person --> beer --
beer -> person ++ : removeItem(beer)
person --> beer --
[<-- beer --

@enduml