@startuml janitor-update
'https://plantuml.com/sequence-diagram

title Update Janitor
hide footbox

participant "janitor : Janitor" as janitor
participant "room : Room" as room
participant "person : Person" as person
participant "door : Door" as door

[-> janitor ++ : update(deltaTime)
janitor -> room ++ : interactJanitor(janitor)
loop person in people
    room -> person ++: interactJanitor(teacher)
    loop door in doors
        person -> door ++: use(person, room)
        return
        alt moved successfully
            return
        end
    end
    return
end
return

@enduml