@startuml link-transistor

title Link Transistors
hide footbox
autoactivate on

participant "transistor1 : Transistor" as tr1
participant "transistor2 : Transistor" as tr2

[-> tr1 : use(transistor2 : Item) 
	tr1 -> tr2 : use(transistor1 : Transistor)
		tr2 -> tr1 : link(transistor2)
		return
	return
return

@enduml