@startuml person-drop-item

title Drop Item
hide footbox
autoactivate on

participant "person : Person" as person
participant "inventory : Inventory" as inventory
participant "room : Room" as room
participant "item : Item" as item

[-> person : dropItem(item)
	person -> inventory : remove(item)
	return
	person -> room : addItem(item)
		room -> item ++: setRoom(room)
		return
	return
return

@enduml
