@startuml person-enter-room
title Person Enter Room
hide footbox
skinparam SequenceReferenceBackgroundColor white
autoactivate on

participant "person : Person" as person
participant "inventory : Inventory" as inv
participant "prev : Room" as prev
participant "next : Room" as next

[-> person : enter(next)
	person -> prev : remove(person)
	return
	loop effect in roomEffects 
		person -> prev : removeEffect(effect)
		return
		person -> next : applyEffect(effect)
		return
	end
	person -> next : add(person)
	return
	person -> inv : setRoom(next)
return
@enduml