@startuml person-enter-room
title Person Enter Room
hide footbox
skinparam SequenceReferenceBackgroundColor white
autoactivate on

participant "person : Person" as person
participant "inventory : Inventory" as inventory

[-> person : enterRoom(room)
	person -> inventory ++: setRoom(room)
		ref over inventory : Update Room for\nItems in the Inventory
	return
return
@enduml