@startuml person-add-item

title Add Item to Person
hide footbox
autoactivate on

participant "person : Person" as person
participant "inventory : Inventory" as inventory

[-> person : addItem(item)
	person -> inventory : add(item)
	return success : bool
return success

@enduml
