@startuml person-update

title Update Person
hide footbox

participant "person : Person" as person
participant "effect : Effect" as effect

[-> person ++: update(deltaTime)
    person -> effect ++: update(deltaTime)
    return
return

@enduml
