@startuml door-sequence
hide footbox

participant "person : Person" as per
participant "item : Item" as item

[-> per ++: Pickup Command

alt there is an item near 
    per -> item ++: Pickup Command
    alt inventory has free space
        item -> per ++: Pickup
    else there is no space
        <-- item ++:
    end
else there is no item near
    <-- item ++:
end

<-- item ++:

@enduml