@startuml remove-item
title Remove Item
hide footbox

participant "object : GameObject" as object
participant "item : Item" as item

[-> object ++: addItem(item)
	create "visitor : RemoveItemVisitor" as visitor
	object -> visitor : object
	object -> item ++ : accept(visitor)
		item -> visitor ++: visit(item)
		return
	return
return

@enduml