@startuml room-update
title Update Room
hide footbox
autoactivate on

participant "room : Room" as room
participant "effect : Effect" as effect
participant "person : Person" as person

[-> room : update(deltaTime)
loop effect in effects
	room -> effect : update(deltaTime)
	return
end
loop person in people
	room -> person : update(deltaTime)
	return
end
return

@enduml