@startuml room-split
title Split Room
hide footbox

participant "room : Room" as r1
[-> r1 ++: split()
	create "newRoom : Room" as r2
	r1 -> r2: effects, capcity
	create  "door: Door" as d
	r1 -> d ++: room, newRoom
		d -> r1 ++ : addDoor(door)
		return
		d -> r2 ++ : addDoor(door)
		return
	return
return newRoom

@enduml