@startuml room-update
title Update Room
hide footbox
autoactivate on
skinparam SequenceReferenceBackgroundColor white

participant "room : Room" as room
participant "effect : Effect" as effect
participant "person : Person" as person
participant "item : Item" as item

[-> room : update(deltaTime)
	loop effect in effects
		room -> effect : update(deltaTime)
		return
	end
	loop person in people
		loop effect in effects
			room -> person ++: applyEffect(effect)
				ref over person: Apply Effect
			return
		end
		room -> person : update(deltaTime)
		return
	end
return

@enduml