@startuml soul-theft
title Soul Theft
hide footbox

participant "student : Student" as s
participant "effect : Effect" as e
participant "item : Item" as i

[-> s ++ : beingAttacked(teacher)
opt teacher is not ignored
	create "visitor : SoulTakingVisitor" as v
	s -> v : student, teacher
	loop effect in effects
		s -> e ++: accept(visitor)
		e -> v ++: visit(BeerEffect)
		v --> e --
		e --> s --
	end
	loop item in items
		s -> i ++: accept(visitor)
		i -> v ++: visit(CodeOfStudies)
		v -> i ++: use(student)
		i --> v --
		opt tvsz saved the student
			v -> s ++ : ignoreTeacher(teacher)
			s --> v --
		end
		v --> i --
		i --> s --
	end

	s -> v ++: takeSoul()
	opt player was not protected
	v -> s ++: eliminate()
	s --> v --
	end 
	v --> s --
end
[<-- s --

@enduml