@startuml split-room
title Split Room
hide footbox
actor Controller
participant "r1 : Room" as r1



Controller -> r1: split()
create participant "r2 : Room" as r2
r1 -> r2: Create
create participant "d: Door" as d
r1 -> d: Create


@enduml