@startuml toxic-room

hide footbox

participant "person : Person" as p
participant "item : Item" as i

[-> p++: knockOut(duration: int)
create "effectVisitor : PersonalEffectVisitor" as ev
p -> ev : new 
loop item in inventory
	p -> i ++: accept(effectVisitor)
	i -> ev ++: visit(this)
	opt protects from toxic gas
		ev -> p ++: protect()
		p --> ev --
	end
	ev --> i --
	i --> p --
end

[<-- p --

@enduml