@startuml transistor-place

title Place Transistor
hide footbox
autoactivate on

actor "person : Person" as p
participant "transistor1 : Transistor" as tr1
participant "transistor2 : Transistor" as tr2

p -> tr1 : use(person)
	opt linked
		tr1 -> p : dropItem(transistor1)
		return room
		tr1 -> tr2 : setTarget(room)
		return
	end
return

@enduml