@startuml transistor
title Link Transistors
hide footbox

participant "student : Student" as s
participant "tr1 : Transistor" as tr1
participant "tr2 : Transistor" as tr2

s ++
s -> tr1 ++: link(tr2)
tr1 -> tr2 ++: link(this)
tr1 <-- tr2--
s <-- tr1--
s -> tr1++: use(this)
s <-- tr1--
s -> tr2 ++: use(this)

create "portal : Door" as p
tr2 -> p: new
tr2 -> p ++: use(student, currentRoom)
tr2 <-- p
tr2 -x p
p--

s <-- tr2--

@enduml