@startuml room-update
title Update Teacher
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "teacher : Teacher" as teacher

[-> teacher ++: update(deltaTime)
	teacher -> teacher : super.update(deltaTime)
	create "visitor : AttackingVisitor" as visitor
	teacher -> visitor : teacher, room
	teacher -> visitor ++: performAttack()
	ref over visitor : Perfrom Attack
	return
return 

@enduml