@startuml use-transistor

title Teleport Using Transistor
hide footbox
autoactivate on

participant "transistor : Transistor" as transistor
participant "person : Person" as p
participant "target : Room" as target

[-> transistor : use(person)
	opt active
		transistor -> target : enter(person)
		target -> p : enterRoom(target)
		return
		return success
		opt success
			transistor -> p : dropItem(transistor)
			return previousRoom
		end
	end
return

@enduml