@startuml pick-up-wet-rag
title Pick Up Wet Rag
hide footbox
autoactivate on

participant "visitor : AddItemVisitor" as visitor
participant "rag : WetRag" as rag

[-> visitor : visit(rag : WetRag)
visitor -> rag : applyEffect(object)
return
return
@enduml