@startuml room-update-gas-and-mask
title Update Room with Student with Mask and Gas
hide footbox
autoactivate on
skinparam SequenceReferenceBackgroundColor white

participant Main
participant "room : Room" as room
participant "student : Student" as student
participant "gasEffect : GasEffect" as gas
participant "maskEffect : MaskEffect" as mask

activate Main
Main -> room : update(1)
    alt Effect over (user input)
    room -> gas : update(1)
        gas -> room : removeEffect(gasEffect)
        return
    return
    room -> student : update(1)
        student -> mask : update(1)
            alt Effect over (user input)
                mask -> student : removeEffect(maskEffect)
                return
            else Effect not over (user input)
            end
        return
    return
    else Effect not over (user input)
    room -> gas : update(1)
    return
    room -> student : applyEffect(gasEffect)
        student -> gas : applyToStudent(student)
            gas -> student : setKnockout(5)
            return
        return
    return
    room -> student : applyEffect(maskEffect)
            student -> mask : applyToStudent(student)
                mask -> student : setKnockout(0)
                return
            return
        return
    room -> student : update(1)
        student -> mask : update(1)
            alt Effect over (user input)
                mask -> student : removeEffect(maskEffect)
                return
            else Effect not over (user input)
            end
       return
    return

    end

return

@enduml