@startuml room-split
title Split Room
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant Main
participant "room : Room" as r1


activate Main
Main -> r1 ++: split()
	create "newRoom : Room" as r2
	r1 -> r2: <<create>> (effects, capacity)
	create  "door: Door" as d
	r1 -> d ++: <<create>> (room, newRoom)
		d -> r1 ++ : addDoor(door)
		return
		d -> r2 ++ : addDoor(door)
		return
	return
	participant "door : oldDoor" as oldDoor
	r1 -> oldDoor ++: move(room, newRoom)
		oldDoor -> r1 ++: removeDoor(oldDoor)
		return
		oldDoor -> r2 ++: addDoor(oldDoor)
		return
	return

return

@enduml