@startuml room-update-gas-and-mask
title Update Room with Student with Mask and Gas
hide footbox
autoactivate on
skinparam SequenceReferenceBackgroundColor white

participant Main
participant "room : Room" as room
participant "student : Student" as student
participant "gasEffect : GasEffect" as gas
participant "maskEffect : MaskEffect" as mask

activate Main
Main -> room : update(1)
	room -> student : update(1)
	    return
	    room -> gas : update(1)
        alt effect over (user input)
		    gas -> room ++: removeEffect(effect)
		    return
        else effect not over (user input)
        gas -> student : applyEffect(gas)
            student -> gas : applyToStudent(student)
                gas -> student : setKnockout(5)
                    student -> mask : knockedOut()
                        mask -> student : setKnockout(0)
                        return
                    return
                return
            return
        return
        end
	return
return

@enduml