@startuml room-merge
title Merge Room
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main
participant "room1 : Room" as r1
participant "room2 : Room" as r2
participant "room3 : Room" as r3
participant "door1 : Door" as door1
participant "door2 : Door" as door2

main++
main-> r1 ++: merge(room2)
    r1 -> r2 ++: moveContents(room1)
        r2 -> r1 ++ : enter(teacher)
        return
    
        r2 -> r1 ++ : addItem(mask)
        return

        r2 -> door2 ++: move(room1, room3)
        return
        r2 -> r2 ++ : removeDoor(door1)
        return
    return
destroy r2
return
@enduml