@startuml student-use-code-of-studies

title Code Of Studies Protection
hide footbox

participant "main : Main" as main
participant "codeOfStudies : CodeOfStudies" as codeOfStudies
participant "student : Student" as student

main++
main-> codeOfStudies ++: useAgainst(target)
	codeOfStudies -> student ++: protectFromTeacher(target)
	return
return

@enduml
