@startuml student-pickup-sliderule

title Student picks up SlideRule
hide footbox

participant "main : Main" as main
participant "student : Student" as student
participant "slideRule : SlideRule" as slide
participant "inventory : Inventory" as inv
activate main

main-> student ++: addItem(slideRule)
    student -> inv ++: add(slideRule)
    return true
    student -> slide ++: setPerson(student)
	    slide -> student ++: pickedUpSlideRule()
            student -> main ++: victory()
            return
        return
	return
return

@enduml