@startuml student-link-transistor

title Link Transistor
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main
participant "transistor1 : Transistor" as transistor1
participant "transistor2 : Transistor" as transistor2

autoactivate on

main++
main-> transistor1 ++: useItem(transistor2)
	transistor1 -> transistor2 ++: link(transistor1)
		transistor2 -> transistor1 ++: setPair(transistor2)
		return
	return
return

@enduml