@startuml student-protected-by-beer
title Student Gets Protected by Beer
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "student : Student" as student
participant "inventory : Inventory" as inventory
participant "beer : Beer" as beer

[-> student ++: interactTeacher(teacher)
	student -> inventory ++: protectFrom(teacher)
        inventory -> beer ++: useAgaints(teacher)
        return
	return
return

@enduml
