@startuml student-use-mask

title Use Mask
hide footbox

participant "main : Main" as main
participant "mask : Mask" as mask
participant "student : Student" as student

main++
main-> mask ++: usePassive()
	create "maskEffect : MaskEffect" as maskEffect
	mask -> maskEffect: <<create>>
	mask -> student ++: addEffect(maskEffect)
	return
return

@enduml
