@startuml student-use-transistor

title Use Transistor
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "main : Main" as main
participant "transistor1 : Transistor" as transistor1
participant "transistor2 : Transistor" as transistor2
participant "targetRoom : Room" as target
participant "person : Person" as person
participant "room : Room" as room

autoactivate on

main++
main-> transistor1 : use()
	alt linked
		transistor1 -> person : dropItem(transistor1)
		return
		transistor1 -> transistor2 : setTarget(room)
		return
	else active
		transistor1 -> person : dropItem(transistor1)
		return
		transistor1 -> target : enter(person)
		opt has capacity
			target -> person : enterRoom(target)
			return
		end
        return
		opt success
			transistor1 -> room ++: leave(person)
			return
		end
	end
return
@enduml
