@startuml teacher-apply-wetrag-effect

title Apply ragEffect to Teacher
hide footbox
skinparam SequenceReferenceBackgroundColor white

participant "teacher : Teacher" as teacher
participant "room : Room" as room

[-> room ++: applyEffect(ragEffect)
    room -> teacher++: setPeaceful(true)
	return
return

@enduml
