@startuml item-code-of-studies-use

title Teacher picks up SlideRule
hide footbox

participant "main : Main" as main
participant "teacher : Teacher" as teacher
participant "slideRule : SlideRule" as slide
activate main

main-> teacher ++: addItem(slideRule)
    teacher -> slide ++: setPerson(teacher) 
	    slide -> teacher ++: pickedUpSlideRule()
        return
    return
return


@enduml