@startuml effects

' left to right direction

interface Updatable {
	+ update(deltaTime : double) : void
}

class Door {
	+ use(person : Person, from : Room) : void
	+ hide() : void
	+ show() : void
}

class Inventory {
	- itemCount : int
	- selectedSlot : int
	+ addItem(item : Item) : bool
	+ removeItem(item : Item) : void
	+ dropSelected(room : Room) : void	
}

package GameObjects {
	abstract GameObject {
		+ applyEffect(effect : Effect) : void
		+ removeEffect(effect : Effect) : void
		+ addItem(item : Item) : void
		+ removeItem(item : Item) : void
	}

	abstract Person {
		- name : String
		+ knockOut() : void
		+ enterRoom(room : Room) : void
		+ applyEffect(effect : GasEffect) : void
	}

	class Student {
		+ beingAttacked(teacher : Teacher) : void
		+ ignoreTeacher(teacher : Teacher) : void
		+ eliminate() : void
	}
	class Teacher {
		
	}

	class Room {
		- capacity : int
		- numOfPeople : int
		+ visitEffects(visitor : EffectVisitor) : void
		+ visitPeople(visitor : PersonVisitor) : void
		+ enter(person : Person) : boolean
		+ leave(person : Person) : void
		+ merge(room : Room) : void
		+ split() : Room
		+ moveContents(room : Room) : void
		+ addDoor(door : Door) : void
		+ hideDoors() : void
		+ showDoors() : void
	}
	
	Updatable <|.- GameObject
	GameObject <|-- Person
	GameObject <|-- Room
	Person <|-- Teacher
	Person <|-- Student

	Room *-o Person
	Room o-o Door
	Person "inventory" *- Inventory
	Inventory "items [0..5]" o-- Item
}


package Items {
	interface Item {
		+ accept(visitor : ItemVisitor) : void
		+ use(target : GameObject) : void
		+ use(target : Item) : void
	}
	
	class SlideRule
	
	class Transistor {
		+ use(person : Person) : void
		+ use(item : Item) : void
		+ use(transistor : Transistor) : void
		+ link(other : Transistor) : void
		+ setTarget(target : Room) : void
	}
	
	class CodeOfStudies {
		- uses : int
	}
	
	class Beer {
	}
	
	class WetRag {
	}
	
	class Mask {
		- uses : int
	}

	class Camembert {
	}

	together {
		Item <|.- SlideRule
		Item <|.- Transistor
		Item <|.- CodeOfStudies
		Item <|.- Beer
		Item <|.- WetRag
		Item <|.- Mask
		Item <|.- Camembert
	}

	Transistor --o Transistor
}

package Effects {
	abstract Effect {
		{abstract} + accept(visitor : EffectVisitor) : void
	}

	class BeerEffect
	class RagEffect
	class GasEffect
	class MaskEffect

	together {
		Effect <|-- BeerEffect
		Effect <|-- RagEffect
		Effect <|-- GasEffect
		Effect <|-- MaskEffect
	}
	
	Updatable <|.- Effect
}


GameObject *-- Effect
Room *-- Item

Room --o Transistor

WetRag o-o RagEffect
Mask o-o MaskEffect
@enduml