@startuml tile-wrapping

package Model {

    package "Base Model" {
        class Room
        abstract Person
        abstract Item
        class Door
        Person <|-- Student
    }

    package "Wrapper" {
        class Game {
            + nextTurn(currentPlayer : Student) : void
            + getRooms() : Room 0..*
            + getPlayers() : Student 0..*
            + getTiles() : Tile 0..*
            + getEntities() : Entity 0..*
        }
        abstract Tile
        class FloorTile
        class DoorTile
        class WallTile

        class Entity
        class ItemEntity {
            - use () : void
            - drop() : void
            - pickUp (PersonEntity) : void
        }

        Tile <|-- FloorTile
        Tile <|-- DoorTile
        Tile <|-- WallTile

        Entity <|-- PersonEntity
        Entity <|-- ItemEntity

        PersonEntity o-- Person
        ItemEntity o-- Item
        Tile o-- Item
        Tile o- Entity

        Game "tiles 0..*" *-- Tile
        Game "entities 0..*" *-- Entity
    }
    Tile o-- Room
    DoorTile o-- Door

    Game "rooms 0..*" *-- Room
    Game "players 1..4" o-- Student

}
package "View" {
    class GameWindow {
        + nextTurn(currentPlayer : Student) : void
    }
    class SidePanel
    class MapView
    GameWindow *-- SidePanel
    GameWindow *-- MapView
    SidePanel *-- PlayerPanel : "playerPanels 4"
    MapView *-- TilePanel : tilePanels 0..*
    }

Game *- GameWindow : gameWindow
package Controller {

    class ControllerClass as "Controller" {
        - nextTurn() : void
        - NPCturn() : void
        - move(Entity, direction) : void
        + use (ItemEntity) : void
        + drop (ItemEntity) : void
        + pickUp (ItemEntity,PersonEntity) : void
    }
    class KeyboardEventListener
    class MouseEventListener
    enum direction {
        up
        down
        left
        right
    }
    ControllerClass --> KeyboardEventListener
    ControllerClass *-- Game : game

    KeyboardEventListener o-- ControllerClass
}
ControllerClass o-- Student : currentPlayer
SidePanel o- PersonEntity : currentPlayer
PlayerPanel --> MouseEventListener
PlayerPanel --o Student : player
PlayerPanel  o-- ControllerClass : controller

Tile o--- TilePanel : tileView
@enduml