@startuml Visitors

title visitors
left to right direction

package Visitors {
	interface EffectVisitor {
		+ visit(effect : BeerEffect) : void
		+ visit(effect : RagEffect) : void
		+ visit(effect : GasEffect) : void
		+ visit(effect : MaskEffect) : void
	}
	interface ItemVisitor {
		+ visit(item : SlideRule) : void
		+ visit(item : transistor) : void
		+ visit(item : CodeOfStudies) : void
		+ visit(item : Beer) : void
		+ visit(item : WetRag) : void
		+ visit(item : Mask) : void
		+ visit(item : Camambert) : void
	}
	interface PersonVisitor {
		+ visit (object : Student) : void
		+ visit (object : Teacher) : void
	}

	class SoulTakingVisitor {
		- protected : bool
		+ visit(effect : BeerEffect) : void
		+ visit(item : CodeOfStudies) : void
		+ takeSoul() : void
	}
	class PoisoningVisitor {
		- protected : bool
		+ visit(item : Mask) : void
		+ visit(effect : MaskEffect) : void
		+ poison() : void
	}
	class AttackingVisitor {
		- canAttack : bool
		+ visit(effect : RagEffect) : void
		+ visit(object : Room) : void
		+ visit(object : Person) : void
	}
	class AddItemVisitor {
		+ visit(item : WetRag) : void
	}
	class RemoveItemVisitor {
		+ visit(item : WetRag) : void
	}
}

abstract GameObject {
	+ applyEffect(effect : Effect) : void
	+ removeEffect(effect : Effect) : void
	+ addItem(item : Item) : void
	+ removeItem(item : Item) : void
}

abstract Person {
	- name : String
	- numItems : int
	+ dropItem(item : Item) : Room
	+ knockOut() : void
	+ enterRoom(room : Room) : void
	+ applyEffect(effect : GasEffect) : void
}

class Student {
	+ beingAttacked(teacher : Teacher) : void
	+ ignoreTeacher(teacher : Teacher) : void
	+ eliminate() : void
}
class Teacher

class Room {
	- capacity : int
	- numOfPeople : int
	+ visitEffects(visitor : EffectVisitor) : void
	+ visitPeople(visitor : PersonVisitor) : void
	+ enter(person : Person) : boolean
	+ leave(person : Person) : void
	+ merge(room : Room) : void
	+ split() : Room
	+ moveContents(room : Room) : void
	+ addDoor(door : Door) : void
	+ hideDoors() : void
	+ showDoors() : void
}

ItemVisitor <|.- SoulTakingVisitor
EffectVisitor <|.- SoulTakingVisitor

ItemVisitor <|.- PoisoningVisitor
EffectVisitor <|.- PoisoningVisitor

EffectVisitor <|.- AttackingVisitor
PersonVisitor <|.- AttackingVisitor

ItemVisitor <|.- AddItemVisitor
ItemVisitor <|.- RemoveItemVisitor

SoulTakingVisitor o-- Teacher
SoulTakingVisitor o-- Student

PoisoningVisitor o-- Person

AttackingVisitor o-- Teacher
AttackingVisitor o-- Room

AddItemVisitor o-- GameObject
RemoveItemVisitor o-- GameObject



@enduml